# Generated by Django 5.0.3 on 2024-06-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_workouts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workouts",
            name="image",
            field=models.ImageField(upload_to="workouts/"),
        ),
    ]
