# Generated by Django 5.0.3 on 2024-06-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_userprogress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workouts",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
