# Generated by Django 5.0.3 on 2024-06-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_workouts_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprogress",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
