# Generated by Django 5.0.3 on 2024-06-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_userprogress_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkoutPlans",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="workouts/")),
                ("description", models.TextField(max_length=500)),
            ],
        ),
    ]
