# Generated by Django 5.0.3 on 2024-06-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_workoutplans"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutplans",
            name="days",
            field=models.IntegerField(choices=[(15, 15), (30, 30)], default=15),
        ),
    ]
