# Generated by Django 5.0.3 on 2024-06-21 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_workoutplans_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutplans",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
