# Generated by Django 5.0.3 on 2024-06-21 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_alter_userprogress_plan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutplans",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
