# Generated by Django 5.0.3 on 2024-06-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_alter_workoutplans_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprogress",
            name="plan",
            field=models.IntegerField(default=15),
        ),
    ]
