# Generated by Django 5.0.3 on 2024-06-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_alter_userprogress_plan"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="workoutplans",
            name="unique_title_days",
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="plan",
            field=models.CharField(
                choices=[("15 days", "15 days"), ("30 days", "30 days")],
                default="15 days",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="workoutplans",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
