# Generated by Django 5.0.3 on 2024-06-21 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_alter_userprogress_plan_alter_workoutplans_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprogress",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.workoutplans"
            ),
        ),
    ]
