# Generated by Django 5.0.3 on 2024-06-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_alter_userprogress_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutplans",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
