# Generated by Django 5.0.3 on 2024-06-21 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_alter_workoutplans_id"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="workoutplans",
            name="unique_title_days",
        ),
    ]
