# Generated by Django 5.0.3 on 2024-06-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_remove_workoutplans_unique_title_days"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprogress",
            old_name="plan",
            new_name="unique_title_days",
        ),
        migrations.AlterField(
            model_name="workoutplans",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddConstraint(
            model_name="workoutplans",
            constraint=models.UniqueConstraint(
                fields=("title", "days"), name="unique_title_days"
            ),
        ),
    ]
